title: ENJOY!! 🚲 + 💻
email: stevenjmoxley@gmail.com
description: This site is dedicated for my blogging and ever learning knowledge of programming and just things that I like
baseurl: ""
url: "http://localhost:4000/"
twitter_username: stevenmox
github_username:  stevenmox
instagram_username: stevenmox
codepen_username: stevenmox

sass:
  sass_dir: _sass
include: ['_pages']
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
