title: ENJOY!
email: stevenjmoxley@gmail.com
description: This site is dedicated for my blogging and ever learning knowledge of programming and just things that I like
baseurl: "/stevenmox"
url: "https://stevenmox.github.io/stevenmox/"
twitter_username: stevenmox
github_username:  stevenmox
instagram_username: stevenmox
codepen_username: stevenmox

sass:
  sass_dir: _sass
include: ['_pages']
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
